name: convert_images
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'images/uploads/**'

permissions:
  contents: write

jobs:
  convertimages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # FORCE STABLE PYTHON: 3.14 is too new and might be causing the dictionary lookup error
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: IIIF Tiling
        uses: glenrobson/iiif-tiler-action@main
        with:
          input-dir-v2: images/uploads/2
          input-dir-v3: images/uploads/3
          output-dir: images
          manifest: images/manifest.json
          url: "https://joshuaortizbaco.com/boundless"

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Adding IIIF image to repository"
            git pull --rebase origin main
            git push origin main
          else
            echo "No changes to commit"
          fi
